### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by GuidoBartoli** [hiarindam/document-image-classification-TL-SG#3]
Other than pretrained weights, are you planning to also provide the reference source code (preprocessing, meta-classifier, etc...) used for the article?

Thanks

**Comment by saikat-roy** [comment]
Hi. Sorry for replying late. Although we didn't have any thoughts on releasing the code (mostly due to it being extremely unpolished), this isn't the first time we're getting the request. We'll try to see if we can do it, but unfortunately we can't promise anything currently.

**Comment by GuidoBartoli** [comment]
Ok, that’s a pity.. thank you anyway.

Have a nice day!
