### ISSUE TITLE
For evaluation, is test set normalized in the same manner as the train set?

### ISSUE THREAD

**Issue by gordon-lim** [hiarindam/document-image-classification-TL-SG#7]
I computed mean and std for rvlcdip to be 0.9919 and 0.1853 so these are the following transforms I'm using for the train set:
`dataset = RvlCdipDataset('labels/train.txt', 
                         'images/', 
                         transform=transforms.Compose([transforms.Resize((224,224)),
                                                       transforms.Normalize(0.9199, 0.1853),
                                                       transforms.Lambda(lambda x: x.repeat(3,1,1))]))`

Do I use the same transforms for the test set?

**Comment by saikat-roy** [comment]
Hi @gordon-lim, I think this [this comment](https://github.com/hiarindam/document-image-classification-TL-SG/issues/4#issuecomment-551321667) will help you best with the preprocessing. I'm sorry but I don't have access to the actual standardization values anymore, so I can't verify the ones you provided. I'm simply trying to point you to others who made the weights work for themselves.

If that doesn't help (eg. you're not using the same framework maybe), then yes in principle you should do the same transforms for the test set.
